#!/bin/bash

if [ ! -f /opt/script/.tomcat_admin_created  && -f /opt/script/create_tomcat_admin_user.sh ]; then
    sh /opt/script/create_tomcat_admin_user.sh
fi

exec ${CATALINA_HOME}/bin/catalina.sh run
